version: '3'

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - 3309:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_DATABASE=weather
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 100

  app:
    build: .
    container_name : app
    ports:
      - 8080:8080
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/weather